import assert from 'node:assert/strict';
import test from 'node:test';
import React from 'react';
import {render} from 'ink-testing-library';
import {ForgeTui, paletteActionIds, parseForm, submitCatalogAction} from '../src/app.tsx';
import {validateAction} from '../src/state.ts';
import {deriveProgress, providerHealthLine} from '../src/components/progress-strip.tsx';

const action=(id:string,fields:any[]=[],extra:any={})=>({id,scope:'factory',label:id,risk:'safe',enabled:true,blockedReason:null,fields,...extra});
const snapshot:any={version:'v1',runner:{activeRunId:null},providers:[{id:'codex',installed:true},{id:'claude',installed:false}],lifecycle:[],alwaysOnDeployments:[],discovery:{revision:1,rooms:[{id:'room-1',title:'Café A',messageCount:1},{id:'room-2',title:'Café B',messageCount:0}],theses:[{id:'thesis-1',roomId:'room-1',stage:'confirmed'},{id:'thesis-2',roomId:'room-2',stage:'proposed'}]},actions:[
 action('room.create',[{name:'title',label:'Título',type:'text',required:true,options:[]}]),
 action('chat.send',[{name:'roomId',label:'Room',type:'text',required:true,options:[]},{name:'text',label:'Mensagem',type:'textarea',required:true,options:[]},{name:'playerId',label:'Executor',type:'select',required:true,options:['claude','codex','grok']}]),
 action('playbook.run',[{name:'playbookId',label:'Playbook',type:'select',required:true,options:['pressure-test','pain-signal-miner']},{name:'thesisId',label:'Tese',type:'text',required:true,options:[]},{name:'playerId',label:'Executor',type:'select',required:true,options:['claude','codex']},{name:'input',label:'Entrada',type:'textarea',required:true,options:[]}]),
	action('chat.stop'),action('thesis.propose'),action('playbook.import'),action('playbook.revise'),action('thesis.confirm',[],{risk:'guarded'}),action('evidence.record'),action('evidence.verify'),action('experiment.create'),action('experiment.complete'),action('build.propose',[],{risk:'guarded'}),
 action('discovery.build.start'),action('build.complete'),action('build.terminate'),action('experiment.validation_asset.attach'),
	action('braga.prepare'),action('braga.export'),action('braga.return.import'),action('acquisition.start',[],{risk:'external'}),action('acquisition.complete'),action('acquisition.terminate'),
 action('spend.approve',[{name:'experimentId',label:'Experimento',type:'text',required:true,options:[]},{name:'requested',label:'Solicitado',type:'number',required:true,options:[]},{name:'ceiling',label:'Teto',type:'number',required:true,options:[]},{name:'why',label:'Justificativa',type:'textarea',required:true,options:[]},{name:'actor',label:'Ator',type:'text',required:true,options:[]},{name:'confirmed',label:'Confirmo',type:'checkbox',required:true,options:[]}],{risk:'external'}),
 action('p4.record',[],{scope:'pipeline:app-1'}),action('p5.decide',[],{scope:'pipeline:app-1'}),action('always-on.prepare',[],{scope:'pipeline:app-1'}),action('always-on.confirm',[],{scope:'pipeline:app-1'}),action('always-on.publish.record',[],{scope:'pipeline:app-1',risk:'external'}),action('always-on.verify',[],{scope:'pipeline:app-1'})
]};
const flush=()=>new Promise(resolve=>setTimeout(resolve,250));
async function waitFor(predicate:()=>boolean,timeoutMs=3000){const started=Date.now();while(!predicate()){if(Date.now()-started>=timeoutMs)throw new Error('timeout aguardando condicao da TUI');await flush();}}
function fakeClient(){const executions:any[]=[];const loads:any[]=[];let emit:(e:any)=>void=()=>{};return {executions,loads,emit:(e:any)=>emit(e),client:{snapshot:async()=>snapshot,room:async(id:string)=>(loads.push(['room',id]),{id,title:id==='room-1'?'Café A':'Café B',messages:[{id:'m',author:'human',text:'ação'}]}),thesis:async(id:string)=>(loads.push(['thesis',id]),{id,stage:'confirmed',evidenceIds:[],experimentIds:[]}),events:async(cb:any,signal:AbortSignal)=>{emit=cb;await new Promise(resolve=>signal.addEventListener('abort',resolve));},execute:async(payload:any)=>(executions.push(payload),{status:'succeeded'}),confirm:async()=>({nonce:'nonce-1'})} as any};}

test('stdin seleciona room e envia chat Unicode com executor escolhido e payload exato',async()=>{const fx=fakeClient();const view=render(<ForgeTui client={fx.client}/>);await flush();view.stdin.write('[B');await waitFor(()=>fx.loads.some(x=>x[0]==='room'&&x[1]==='room-2'));view.stdin.write(':');await flush();view.stdin.write('[B');await flush();view.stdin.write('\r');await flush();assert.match(view.lastFrame()||'',/FORM · chat\.send/);view.stdin.write('Olá ação çã');await flush();view.stdin.write('\t');await flush();view.stdin.write('[C');await flush();view.stdin.write('\r');await flush();assert.match(view.lastFrame()||'',/REVISÃO/);view.stdin.write('\r');await flush();assert.equal(fx.executions.length,1);assert.deepEqual(fx.executions[0].input,{roomId:'room-2',text:'Olá ação çã',playerId:'codex'});view.unmount();});

test('digitar no prompt principal e Enter envia uma só vez como Codex/Claude sem Tab nem paleta',async()=>{const fx=fakeClient();const view=render(<ForgeTui client={fx.client}/>);await flush();view.stdin.write('Quero validar esta ideia');await flush();assert.match(view.lastFrame()||'',/[>›] Quero validar esta ideia/);view.stdin.write('\r');view.stdin.write('\r');await waitFor(()=>fx.executions.length===1);assert.deepEqual(fx.executions[0].input,{roomId:'room-1',text:'Quero validar esta ideia',playerId:'codex'});await waitFor(()=>/Digite sua ideia ou mensagem/.test(view.lastFrame()||''));assert.equal(fx.executions.length,1);view.unmount();});

test('primeira mensagem cria uma room automaticamente e envia o mesmo texto',async()=>{let current:any={...snapshot,version:'v-empty',discovery:{revision:null,rooms:[],theses:[]}};const executions:any[]=[];const client:any={snapshot:async()=>current,room:async(id:string)=>({id,title:'Minha primeira ideia',messages:[]}),thesis:async()=>null,events:async(_cb:any,signal:AbortSignal)=>new Promise(resolve=>signal.addEventListener('abort',resolve)),confirm:async()=>({nonce:'n'}),execute:async(payload:any)=>{executions.push(payload);if(payload.actionId==='room.create'){current={...current,version:'v-room',discovery:{...current.discovery,revision:1,rooms:[{id:'room-new',title:payload.input.title,messageCount:0}]}};return {status:'succeeded',result:{id:'room-new'}};}return {status:'succeeded'};}};const view=render(<ForgeTui client={client}/>);await flush();view.stdin.write('Uma loja de prompts para creators');await flush();view.stdin.write('\r');await waitFor(()=>executions.length===2);assert.deepEqual(executions.map(item=>item.actionId),['room.create','chat.send']);assert.deepEqual(executions[0].input,{title:'Uma loja de prompts para creators'});assert.deepEqual(executions[1].input,{roomId:'room-new',text:'Uma loja de prompts para creators',playerId:'codex'});await waitFor(()=>/mensagem enviada/.test(view.lastFrame()||''));view.unmount();});

test('ajuda explica teclado sem fingir suporte a clique ou exigir Tab',async()=>{const fx=fakeClient();const view=render(<ForgeTui client={fx.client}/>);await flush();view.stdin.write('?');await flush();assert.match(view.lastFrame()||'',/Não precisa clicar nem usar Tab/);assert.match(view.lastFrame()||'',/mouse não é usado/i);view.stdin.write('?');view.stdin.write('continua digitando');await flush();assert.match(view.lastFrame()||'',/[>›] continua digitando/);view.unmount();});

test('stdin edita room, cancela form e stream/resize permanecem renderizáveis',async()=>{const fx=fakeClient();const view=render(<ForgeTui client={fx.client}/>);await flush();view.stdin.write(':');await flush();view.stdin.write('\r');await flush();assert.match(view.lastFrame()||'',/FORM · room\.create/);view.stdin.write('Nova sala');await flush();view.stdin.write('\r');await flush();assert.match(view.lastFrame()||'',/REVISÃO/);view.stdin.write('');await flush();view.stdin.write('');await flush();assert.equal(fx.executions.length,0);fx.emit({type:'chat.chunk',roomId:'room-1',text:' transmissão çã'});await flush();assert.match(view.lastFrame()||'',/transmissão çã/);view.rerender(<ForgeTui client={fx.client}/>);await flush();assert.match(view.lastFrame()||'',/FORGE NEXUS/);view.unmount();});

test('JSON/número/select são convertidos, blocked/why/required falham e nonce externo é enviado',async()=>{const jsonAction:any=action('playbook.run',[{name:'input',label:'Entrada',type:'textarea',required:true,options:[]},{name:'maxTurns',label:'Turnos',type:'number',required:true,options:[]},{name:'playerId',label:'Executor',type:'select',required:true,options:['claude']}]);assert.deepEqual(parseForm(jsonAction,{input:'{"dor":true}',maxTurns:'3',playerId:'claude'}),{input:{dor:true},maxTurns:3,playerId:'claude'});assert.throws(()=>parseForm(jsonAction,{input:'{',maxTurns:'3',playerId:'claude'}),/JSON válido/);assert.throws(()=>validateAction({...jsonAction,id:'spend.approve'},{}),/obrigatório|why/);assert.throws(()=>validateAction({...jsonAction,enabled:false,blockedReason:'E2 ausente'},{}),/E2 ausente/);const calls:any[]=[];const client:any={confirm:async()=>({nonce:'nonce-x'}),execute:async(p:any)=>(calls.push(p),{})};await submitCatalogAction({client,snapshot,action:{...action('publish.start'),risk:'external'},input:{}});assert.equal(calls[0].confirmation,'nonce-x');});

test('tese guiada compõe o contrato sem JSON e Ctrl+J mantém o modo avançado',()=>{const thesis:any=action('thesis.propose',[{name:'roomId',label:'Room',type:'text',required:true,options:[]},{name:'draft',label:'Tese',type:'json',required:true,options:[]},{name:'sourceMessageIds',label:'Mensagens',type:'json',required:false,options:[]}]);const guided=parseForm(thesis,{roomId:'room-1','draft.buyer':'PMEs','draft.user':'operadores','draft.painfulJob':'perdem tempo','draft.currentAlternative':'planilha','draft.reachableSegment':'clientes locais','draft.channel':'WhatsApp','draft.fatalAssumption':'não pagam','draft.offer':'piloto pago',sourceMessageIds:'m1,m2'});assert.deepEqual(guided,{roomId:'room-1',draft:{buyer:'PMEs',user:'operadores',painfulJob:'perdem tempo',currentAlternative:'planilha',reachableSegment:'clientes locais',channel:'WhatsApp',fatalAssumption:'não pagam',offer:'piloto pago'},sourceMessageIds:['m1','m2']});assert.deepEqual(parseForm(thesis,{roomId:'room-1',draft:'{"buyer":"PMEs"}',sourceMessageIds:'[]'},true),{roomId:'room-1',draft:{buyer:'PMEs'},sourceMessageIds:[]});});

test('palette expõe discovery, pós-build, Braga e acquisition pelos IDs reais do catálogo',()=>{const required=['chat.stop','thesis.propose','discovery.build.start','build.complete','build.terminate','experiment.validation_asset.attach','braga.prepare','braga.export','braga.return.import','acquisition.start','acquisition.complete','acquisition.terminate','spend.approve'];assert.deepEqual(paletteActionIds.filter(id=>required.includes(id)),required);assert.ok(paletteActionIds.every(id=>snapshot.actions.some((a:any)=>a.id===id)));});

test('spend transforma números/checkbox, confirma no servidor e envia payload exato',async()=>{const spend=snapshot.actions.find((item:any)=>item.id==='spend.approve');const input=parseForm(spend,{experimentId:'experiment-1',requested:'50',ceiling:'40',why:'Teste controlado',actor:'gui',confirmed:'true'});assert.deepEqual(input,{experimentId:'experiment-1',requested:50,ceiling:40,why:'Teste controlado',actor:'gui',confirmed:true});const calls:any[]=[];const client:any={confirm:async(payload:any)=>(calls.push(['confirm',payload]),{nonce:'nonce-spend'}),execute:async(payload:any)=>(calls.push(['execute',payload]),{status:'succeeded'})};await submitCatalogAction({client,snapshot,action:spend,input});assert.deepEqual(calls[0],['confirm',{actionId:'spend.approve',appId:null,stateVersion:'v1'}]);assert.equal(calls[1][1].confirmation,'nonce-spend');assert.deepEqual(calls[1][1].input,input);});

test('faixa persistente mostra etapa, falta, próxima ação e health local honesto',()=>{const thesis={id:'thesis-1',stage:'confirmed',experimentIds:[],gates:{e1:{ok:false,unmet:['pain']},e2:{ok:false,unmet:['reach']}}};const progress=deriveProgress(snapshot,'room-1',thesis);assert.equal(progress.label,'E1 + E2');assert.match(progress.requirement,/pain/);assert.equal(progress.nextActionId,'evidence.record');assert.equal(providerHealthLine(snapshot),'codex:cli-pronta · claude:ausente');const deploySnapshot={...snapshot,lifecycle:[{appId:'app-1',p5:{decision:'scale'}}],alwaysOnDeployments:[{appId:'app-1',status:'published'}]};const deploy=deriveProgress(deploySnapshot,'room-1',{...thesis,buildId:'build-1',build:{appId:'app-1',status:'completed'},acquisitionId:'acq-1',experimentIds:['experiment-1'],gates:{e1:{ok:true},e2:{ok:true},e3:{ok:true}}});assert.equal(deploy.label,'DEPLOY · published');assert.equal(deploy.nextActionId,'always-on.verify');});

test('publicação Always-On usa escopo do app e nonce externo',async()=>{const publish=snapshot.actions.find((item:any)=>item.id==='always-on.publish.record');const calls:any[]=[];const client:any={confirm:async(payload:any)=>(calls.push(['confirm',payload]),{nonce:'nonce-deploy'}),execute:async(payload:any)=>(calls.push(['execute',payload]),{})};await submitCatalogAction({client,snapshot,action:publish,input:{revision:'abc'}});assert.equal(calls[0][1].appId,'app-1');assert.equal(calls[1][1].appId,'app-1');assert.equal(calls[1][1].confirmation,'nonce-deploy');});

test('Braga return é convertido de JSON antes do envio',()=>{const braga:any=action('braga.return.import',[{name:'result',label:'Retorno',type:'textarea',required:true,options:[]},{name:'actor',label:'Ator',type:'text',required:true,options:[]}]);assert.deepEqual(parseForm(braga,{result:'{"schemaVersion":1,"experimentId":"experiment-1","spend":0}',actor:'gui'}),{result:{schemaVersion:1,experimentId:'experiment-1',spend:0},actor:'gui'});});

test('stale/error não silenciam',async()=>{const client:any={execute:async()=>{throw Object.assign(new Error('estado stale'),{code:'state_stale'});},confirm:async()=>({nonce:'n'})};await assert.rejects(()=>submitCatalogAction({client,snapshot,action:action('room.create'),input:{title:'x'}}),/stale/);});
