import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { createDiscoveryWorkspace } from "../discovery/workspace.mjs";
import { createEngineManager, JOBS_BY_CAPABILITY } from "../engine.mjs";

const draft={buyer:"síndico",user:"técnico",painfulJob:"provar PMOC",currentAlternative:"planilha",reachableSegment:"administradoras",channel:"WhatsApp",fatalAssumption:"pagará",offer:"auditoria"};
const brief={hypothesisToTest:"pagará por auditoria",minimalScope:"landing + formulário",capability:"static",profile:"pmoc",blueprint:"generic",channel:"WhatsApp",postBuildEvent:{name:"lead_submitted",required:true},successCriteria:"2 leads",killCriteria:"0 leads em 7d"};
function fixture({throwStart=false}={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),"forge-build-bridge-"));let seq=0;const starts=[];const engineManager={startFromDiscovery(input){starts.push(structuredClone(input));if(throwStart)throw new Error("start falhou");return {appId:`app-${starts.length}`,runId:`run-${starts.length}`};}};const workspace=createDiscoveryWorkspace({root,engineManager,now:()=>"2026-07-18T12:00:00.000Z",idFactory:p=>`${p}-${++seq}`});return{root,workspace,starts,engineManager};}
function thesis(workspace,title="T"){const room=workspace.createRoom({title});return workspace.confirmThesis({thesisId:workspace.proposeThesis({roomId:room.id,sourceMessageIds:[],draft}).id,actor:"gui"});}
function evidence(workspace,thesisId,validation,{synthetic=false}={}){const item=workspace.recordEvidence({thesisId,evidence:{observation:validation,inference:"sinal",validation,polarity:"supporting",source:synthetic?"internal://sim":"https://example.com/"+validation,date:"2026-07-18",sensitivity:synthetic?"internal":"public",synthetic}});workspace.verifyEvidence({evidenceId:item.id,actor:"gui",decision:"verified"});return item;}
function eligible(workspace,t){return [evidence(workspace,t.id,"pain"),evidence(workspace,t.id,"reach"),evidence(workspace,t.id,"action")];}
function realRoot(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"forge-build-engine-"));fs.mkdirSync(path.join(root,"maestro"),{recursive:true});fs.writeFileSync(path.join(root,"maestro","roster.json"),JSON.stringify({version:"2.0",players:[{id:"fake-1",face:"🧪",name:"Fake",cli:"fake",model:"default",modelLabel:"Fake",effort:"low",jobs:[],roles:[]}],teams:{"dry-run":{emoji:"🧪",label:"fake executor",dispatch:{default:"fake-1"},fallbacks:{}}}}),"utf8");return root;}
const realManager=root=>createEngineManager({root,emitLog:()=>{},emitPipeline:()=>{}});

test("synthetic+E1 e E1 sem E2 falham; E1+E2 propõe sem iniciar",()=>{const{workspace,starts}=fixture();const t=thesis(workspace);evidence(workspace,t.id,"pain");evidence(workspace,t.id,"reach");evidence(workspace,t.id,"action",{synthetic:true});assert.throws(()=>workspace.proposeBuild({thesisId:t.id,brief,actor:"gui"}),/action/);assert.equal(starts.length,0);evidence(workspace,t.id,"action");const proposal=workspace.proposeBuild({thesisId:t.id,brief,actor:"gui"});assert.equal(starts.length,0);assert.equal(Object.isFrozen(proposal),true);assert.deepEqual(proposal.evidenceRefs,workspace.gatesFor(t.id).build.evidenceRefs);});

test("aprovação explícita inicia uma vez, persiste vínculo e restart não duplica",()=>{const fx=fixture();const t=thesis(fx.workspace);eligible(fx.workspace,t);const proposal=fx.workspace.proposeBuild({thesisId:t.id,brief,actor:"gui"});assert.throws(()=>fx.workspace.startBuild({thesisId:t.id,startOptions:{},actor:"gui"}),/approval/i);const build=fx.workspace.startBuild({thesisId:t.id,startOptions:{approved:true},actor:"gui"});assert.equal(fx.starts.length,1);assert.equal(build.appId,"app-1");assert.equal(build.runId,"run-1");assert.equal(fx.starts[0].buildProposal.id,proposal.id);const restarted=createDiscoveryWorkspace({root:fx.root,engineManager:fx.engineManager});const same=restarted.startBuild({thesisId:t.id,startOptions:{approved:true},actor:"gui"});assert.equal(same.id,build.id);assert.equal(fx.starts.length,1);});

test("reserva building é global e falha de start libera atomicamente",()=>{const failing=fixture({throwStart:true});const a=thesis(failing.workspace,"A");eligible(failing.workspace,a);failing.workspace.proposeBuild({thesisId:a.id,brief,actor:"gui"});assert.throws(()=>failing.workspace.startBuild({thesisId:a.id,startOptions:{approved:true},actor:"gui"}),/start falhou/);assert.equal(failing.workspace.snapshot().builds.some(b=>b.status==="building"||b.status==="starting"),false);});

test("segundo build bloqueia; complete exige artefato e instrumentação observada e libera slot",()=>{const fx=fixture();const a=thesis(fx.workspace,"A"),b=thesis(fx.workspace,"B");for(const t of[a,b]){eligible(fx.workspace,t);fx.workspace.proposeBuild({thesisId:t.id,brief,actor:"gui"});}const build=fx.workspace.startBuild({thesisId:a.id,startOptions:{approved:true},actor:"gui"});assert.throws(()=>fx.workspace.startBuild({thesisId:b.id,startOptions:{approved:true},actor:"gui"}),/WIP.*build/);assert.throws(()=>fx.workspace.completeBuild({buildId:build.id,url:"https://app.test",instrumentationObserved:false,actor:"gui"}),/instrumentação/);const done=fx.workspace.completeBuild({buildId:build.id,url:"https://app.test",instrumentationObserved:true,actor:"gui"});assert.equal(done.status,"completed");assert.equal(fx.workspace.getThesis(a.id).stage,"acquisition_ready");assert.doesNotThrow(()=>fx.workspace.startBuild({thesisId:b.id,startOptions:{approved:true},actor:"gui"}));});

test("asset de validação antes de E2 não inicia pipeline",()=>{const{workspace,starts}=fixture();const t=thesis(workspace);const exp=workspace.createExperiment({thesisId:t.id,experiment:{hypothesis:"h",method:"concierge",audience:"síndicos",expectedAction:"reply",successCriteria:"1",killCriteria:"0",window:"7d",costCap:0}});const asset=workspace.attachValidationAsset({experimentId:exp.id,asset:{type:"landing",url:"https://example.com/landing"},actor:"gui"});assert.equal(asset.type,"landing");assert.equal(starts.length,0);assert.equal(workspace.snapshot().experiments[0].validationAssets.length,1);});

test("BuildProposal e contexto persistido não mudam por referências retornadas",()=>{const fx=fixture();const t=thesis(fx.workspace);eligible(fx.workspace,t);const mutable=structuredClone(brief);const proposal=fx.workspace.proposeBuild({thesisId:t.id,brief:mutable,actor:"gui"});assert.equal(Object.isFrozen(proposal.evidenceRefs),true);assert.equal(Object.isFrozen(proposal.postBuildEvent),true);assert.throws(()=>proposal.evidenceRefs.push("forjado"),TypeError);assert.throws(()=>{proposal.postBuildEvent.name="forjado";},TypeError);mutable.postBuildEvent.name="mudou-fora";const stored=fx.workspace.getThesis(t.id).buildProposal;assert.equal(stored.postBuildEvent.name,"lead_submitted");const returned=fx.workspace.snapshot();returned.theses[0].buildProposal.evidenceRefs.push("forjado");assert.deepEqual(fx.workspace.getThesis(t.id).buildProposal.evidenceRefs,stored.evidenceRefs);fx.workspace.startBuild({thesisId:t.id,startOptions:{approved:true},actor:"gui"});fx.starts[0].buildProposal.postBuildEvent.name="mutado-pelo-engine";assert.equal(fx.workspace.getThesis(t.id).buildProposal.postBuildEvent.name,"lead_submitted");});

test("terminação explícita audita kill/failure, preserva vínculo e libera WIP",()=>{for(const status of ["killed","failed"]){const fx=fixture();const a=thesis(fx.workspace,"A"),b=thesis(fx.workspace,"B");for(const t of [a,b]){eligible(fx.workspace,t);fx.workspace.proposeBuild({thesisId:t.id,brief,actor:"gui"});}const build=fx.workspace.startBuild({thesisId:a.id,startOptions:{approved:true},actor:"gui"});const terminal=fx.workspace.terminateBuild({buildId:build.id,status,reason:`motivo ${status}`,actor:"revisor"});assert.equal(terminal.status,status);assert.equal(terminal.reason,`motivo ${status}`);assert.equal(terminal.terminatedBy,"revisor");const stored=fx.workspace.getThesis(a.id);assert.equal(stored.buildId,build.id);assert.equal(stored.history.at(-1).buildId,build.id);assert.equal(stored.history.at(-1).reason,`motivo ${status}`);assert.doesNotThrow(()=>fx.workspace.startBuild({thesisId:b.id,startOptions:{approved:true},actor:"gui"}));assert.throws(()=>fx.workspace.terminateBuild({buildId:build.id,status:"killed",reason:"de novo",actor:"gui"}),/somente build ativo/);}});

test("createEngineManager persiste discovery mínimo, recupera idempotente e mantém start legado",()=>{const root=realRoot();let manager=realManager(root);try{const proposal={id:"proposal-real",hypothesisToTest:"validar concierge PMOC",minimalScope:"landing",capability:"static",profile:"generic",blueprint:"generic",channel:"WhatsApp",postBuildEvent:{name:"lead_submitted"},successCriteria:"2 leads",killCriteria:"0 leads",evidenceRefs:["ev-pain","ev-reach","ev-action"]};const first=manager.startFromDiscovery({thesisId:"thesis-real",buildProposal:proposal,appId:"discovery-real",team:"dry-run",dryRun:true,controlMode:"manual"});assert.deepEqual(first.jobs,["FOUNDATION","DS-GEN","L1/B1","L1/B2","L1/B3","L1/B5","SIMULATE"]);assert.equal(first.jobs.includes("L0/P0"),false);assert.equal(first.jobs.includes("L0/P1"),false);assert.deepEqual(first.discoveryContext,{thesisId:"thesis-real",buildProposal:proposal});proposal.evidenceRefs.push("forjado");assert.deepEqual(manager.snapshot()["discovery-real"].discoveryContext.buildProposal.evidenceRefs,["ev-pain","ev-reach","ev-action"]);manager.stop("discovery-real");manager=realManager(root);const recovered=manager.startFromDiscovery({thesisId:"thesis-real",buildProposal:{...proposal,evidenceRefs:["ev-pain","ev-reach","ev-action"]},appId:"discovery-real",team:"dry-run",dryRun:true,controlMode:"manual"});assert.equal(recovered.runId,first.runId);assert.deepEqual(recovered.discoveryContext,first.discoveryContext);const legacy=manager.start({idea:"produto legado",appId:"legacy-real",team:"dry-run",capability:"static",dryRun:true,controlMode:"manual"});assert.deepEqual(legacy.jobs,JOBS_BY_CAPABILITY.static);assert.equal(legacy.jobs.includes("L0/P0"),true);assert.equal(legacy.jobs.includes("L0/P1"),true);manager.stop("legacy-real");}finally{fs.rmSync(root,{recursive:true,force:true});}});
